server:
    port: "8080"
    mode: release
database:
    host: rm-bp18v50636683o025go.mysql.rds.aliyuncs.com
    port: "3306"
    user: schedule_system_v3
    password: HsGy3e2T3X4zhNk8JC45ePTb5HrrWda7
    dbname: schedule_system_v3
    charset: utf8mb4
jwt:
    secret: schedule-system-secret-key
    expire: 168
site:
    domain: https://ba0ef1631b5b4535bd920b7a7ea3db0b--8080.ap-shanghai2.cloudstudio.club/
installed: true
